### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by boxochi** [BoB11-TEAM-bobalkkagi/bobalkkagi#3]
[2023-03-12 13:00:37.290870] Unpacking done...
Unpacking Runtime: [0:26:14.338330]
[Create] Dumpfile!
[2023-03-12 13:00:37.312853] Unwrapping Start...
Traceback (most recent call last):
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python39\Scripts\bobalkkagi.exe\__main__.py", line 7, in <module>
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python39\lib\site-packages\bobalkkagi\application.py", line 14, in main
    fire.Fire(run_Bobalkkagi)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python39\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python39\lib\site-packages\fire\core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python39\lib\site-packages\fire\core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python39\lib\site-packages\bobalkkagi\application.py", line 51, in run_Bobalkkagi
    unwrap(dump, OrignalEntryPoint)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python39\lib\site-packages\bobalkkagi\unwrapping.py", line 8, in unwrap
    unwrapping(dumps, OEP)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python39\lib\site-packages\bobalkkagi\util_unwrap.py", line 592, in unwrapping
    emulate_start()
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python39\lib\site-packages\bobalkkagi\util_unwrap.py", line 535, in emulate_start
    call_emulate_rip(uc , rip)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python39\lib\site-packages\bobalkkagi\util_unwrap.py", line 447, in call_emulate_rip
    uc.emu_start(GLOBAL_VAR.ImageBaseStart + rip, GLOBAL_VAR.ImageBaseStart +rip+ 0x20000)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python39\lib\site-packages\unicorn\unicorn.py", line 550, in emu_start
    raise self._hook_exception
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python39\lib\site-packages\unicorn\unicorn.py", line 392, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python39\lib\site-packages\unicorn\unicorn.py", line 663, in _hookcode_cb
    cb(self, address, size, data)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python39\lib\site-packages\bobalkkagi\util_unwrap.py", line 359, in hooking_code
    if not (GLOBAL_VAR.themida[1] <= address and address < (GLOBAL_VAR.themida[1]+GLOBAL_VAR.themida[2])):
IndexError: list index out of range

**Comment by hackerhoon** [comment]
I want to know your input file and arguments! I try to fix bug in this week~

**Comment by boxochi** [comment]
was this file:
https://drive.google.com/file/d/1GJCC9f4AvjuMsvEBpvTcGbldPNuaPHnP/view
also i need to make valid license for this app,if you can help me i will donate bro <3
the license is in a file named bwe.dat

**Comment by hackerhoon** [comment]
As the detailed reason is written in the email I sent. If the(.dat input)work is completely weird, it will take a lot of time.

**Comment by boxochi** [comment]
its not .dat file bro,its .exe file which have a license file named bwe.dat i answered you in mail 
thank you

**Comment by hackerhoon** [comment]
it means the .exe file work with bwe.dat file?

**Comment by boxochi** [comment]
yes bwe.dat is license of bwe.exe  but in trial mode there is no bwe.dat,its mean we are trial user
we need to unpack bwe.exe and make valid license file (bwe.dat)

**Comment by boxochi** [comment]
running exe without bwe.dat
![Screenshot 2023-03-14 125708](https://user-images.githubusercontent.com/14182674/224956963-9dee4121-3422-443f-9a01-7c2444f43a94.png)

after this i maked bwe.dat next to bwe.exe and message changed like this
![Screenshot 2023-03-14 125556](https://user-images.githubusercontent.com/14182674/224957277-db0a94f6-8d73-40ff-bc74-38591bbcdcf7.png)

**Comment by hackerhoon** [comment]
[2023-03-12 13:00:37.290870] Unpacking done...
Unpacking Runtime: [0:26:14.338330]
[Create] Dumpfile!
In your log, unpacking is successed but the api unwrapping is failed. so it need to analyze dumpfile what wrapping pattern is existed. 
If the license authentication part is virtualized, it will not be of much help.

**Comment by boxochi** [comment]
nice so your app is working good for unpacking mistake is from me !!
so what can i do for this app ?help me for valid license please..
can you check code for valid license for my hwid?

**Comment by hackerhoon** [comment]
if you have analysis Environment (ex. IDA, https://github.com/x64dbg/ScyllaHide) you can analyze the dumpfile.
As I said, it will be very difficult to know the original code if it is virtualized. 
The de-virtualization has not yet been implemented, and there are many levels of thiemida virtualization

**Comment by boxochi** [comment]
yes i have,i checked file with x64dbg and i found bwe.dat file as license file
but i am not pro in unpacking and specially de-virtualization
help me i will pay for your hard work <3

**Comment by hackerhoon** [comment]
I'll try, but there's no perfect way to de-virtualization now, so I hope you don't have high expectations.

**Comment by boxochi** [comment]
thank you man,I believe in your science
if you need to use app in trial mode more than once tell me i have trick
