### ISSUE TITLE
Traceback

### ISSUE THREAD

**Issue by illegal-instruction-co** [BoB11-TEAM-bobalkkagi/bobalkkagi#4]
```
Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\bobalkkagi\__main__.py", line 4, in <module>
    main()
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\bobalkkagi\application.py", line 14, in main
    fire.Fire(run_Bobalkkagi)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\fire\core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\fire\core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\bobalkkagi\application.py", line 50, in run_Bobalkkagi
    dump, OrignalEntryPoint = unpack(protectedFile, verbose, mode, oep)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\bobalkkagi\unpacking.py", line 214, in unpack
    PE_Loader(uc, program, GLOBAL_VAR.ImageBaseStart, oep)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\bobalkkagi\loader.py", line 47, in PE_Loader
    sectionSize, sectionInfo = Section(uc, pe, originBase, oep)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\bobalkkagi\loader.py", line 171, in Section
    GLOBAL_VAR.SectionInfo.append([sectionName, base + section.VirtualAddress, section.Misc_VirtualSize, PrivChange(priv)])
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\bobalkkagi\loader.py", line 151, in PrivChange
    return changeDic[privilege]
KeyError: 0
```

**Comment by hackerhoon** [comment]
what is your input?

**Comment by illegal-instruction-co** [comment]
> what is your input?

email ?

**Comment by hackerhoon** [comment]
could you use google drive file share?

**Comment by illegal-instruction-co** [comment]
> could you use google drive file share?

I can use, but the sharing binary on this issue is not a good option.

**Comment by hackerhoon** [comment]
the binary is malware?

my email is gkswlgns21@gmail.com

**Comment by illegal-instruction-co** [comment]
> e binary is malware?

Im not sure yet.

Sent by mail.

**Comment by illegal-instruction-co** [comment]
any update?
