### ISSUE TITLE
Unwrapping failed

### ISSUE THREAD

**Issue by xsiravia** [BoB11-TEAM-bobalkkagi/bobalkkagi#5]
> python3 bobalkkagi protected.exe --verbose t

.....

Unwrapping Start...
```py
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\ntquery\Desktop\bobalkkagi-master\bobalkkagi\__main__.py", line 4, in <module>
    main()
  File "C:\Users\ntquery\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\bobalkkagi\application.py", line 14, in main
    fire.Fire(run_Bobalkkagi)
  File "C:\Users\ntquery\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Users\ntquery\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\fire\core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "C:\Users\ntquery\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\fire\core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "C:\Users\ntquery\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\bobalkkagi\application.py", line 51, in run_Bobalkkagi
    unwrap(dump, OrignalEntryPoint)
  File "C:\Users\ntquery\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\bobalkkagi\unwrapping.py", line 8, in unwrap
    unwrapping(dumps, OEP)
  File "C:\Users\ntquery\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\bobalkkagi\util_unwrap.py", line 592, in unwrapping
    emulate_start()
  File "C:\Users\ntquery\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\bobalkkagi\util_unwrap.py", line 530, in emulate_start
    uc.mem_write(0x140000000, origin_data)
  File "C:\Users\ntquery\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\unicorn\unicorn.py", line 586, in mem_write
    raise UcError(status)
unicorn.unicorn.UcError: Invalid memory write (UC_ERR_WRITE_UNMAPPED)
```

**Comment by hackerhoon** [comment]
unwrapping  function is not perfect. it may be another pattern of api wrapping or emulator problem (some function need api return value, so unicorn engine is not good at unwrapping. if we have a lot of time we use disasm3 or capstone to unwrapp) 

and I join another project so, I don't know when I update my tool. ㅠ
