### ISSUE TITLE
Unicorn.py ImportError: ERROR: fail to load the dynamic library.

### ISSUE THREAD

**Issue by LuckyCat17** [BoB11-TEAM-bobalkkagi/bobalkkagi#7]
Hello when im trying to launch bobalkkagi for unpack an .exe gives my this error 
`Traceback (most recent call last):
  File "C:\Users\Dario\AppData\Local\Programs\Python\Python310-32\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Dario\AppData\Local\Programs\Python\Python310-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Dario\AppData\Local\Programs\Python\Python310-32\Scripts\bobalkkagi.exe\__main__.py", line 4, in <module>
  File "C:\Users\Dario\AppData\Local\Programs\Python\Python310-32\lib\site-packages\bobalkkagi\application.py", line 3, in <module>
    from .unpacking import unpack
  File "C:\Users\Dario\AppData\Local\Programs\Python\Python310-32\lib\site-packages\bobalkkagi\unpacking.py", line 1, in <module>
    from unicorn import *
  File "C:\Users\Dario\AppData\Local\Programs\Python\Python310-32\lib\site-packages\unicorn\__init__.py", line 4, in <module>
    from .unicorn import Uc, uc_version, uc_arch_supported, version_bind, debug, UcError, __version__
  File "C:\Users\Dario\AppData\Local\Programs\Python\Python310-32\lib\site-packages\unicorn\unicorn.py", line 114, in <module>
    raise ImportError("ERROR: fail to load the dynamic library.")
ImportError: ERROR: fail to load the dynamic library.`

**Comment by mcbovice** [comment]
Use python3. Python3 -m pip install unicorn
